package drools.test
import com.github.simoant.drools.analyzer.*
import com.github.simoant.drools.analyzer.utils.*
import com.github.simoant.drools.analyzer.model.DataRequest
import com.github.simoant.drools.analyzer.model.AnalyzerResponse
dialect "java"

global Context ctx;

rule FirstRule
when
    $obj: TestInput($value: value)
then
    DataRequest dr = new DataRequest("first", "first request", true, false);
    ctx.log("First rule");
    insertLogical(dr);
 end

rule SecondRule
when
    $obj: FirstTestObject()
then
    DataRequest dr2 = new DataRequest("second", "first request", true, false);
    insert(new IntermediateDecision());
    insertLogical(dr2);
    ctx.log("Second rule");
 end

rule ThirdRule
when
    $obj: SecondTestObject()
    $inter: IntermediateDecision()
then
    retract($inter);
    AnalyzerResponse ar = new AnalyzerResponse("response");
    insert(ar);
    ctx.log("Third rule");
 end