package drools.test
import com.github.simoant.drools.analyzer.*
import com.github.simoant.drools.analyzer.utils.*
import com.github.simoant.drools.analyzer.model.DataRequest
dialect "java"

global Context ctx;

rule FirstRule
when
    $obj: TestInput($value: value)
then
    DataRequest dr = new DataRequest("no_data", "first request", true, false);
//    DataRequest dr2 = new DataRequest("second", "second request", true);
    ctx.log("First rule");
    insertLogical(dr);
//    insertLogical(dr2);
 end

rule SecondRule
when
    $obj: FirstTestObject()
then
    ctx.log("Second rule");
 end